### ISSUE TITLE
Contract result does not contain all amendments

### ISSUE THREAD

**Issue by nickjevershed** [austender/austender-ocds-api#3]
Result from API only has 10 contract entries:

https://api.tenders.gov.au/ocds/findById/CN269296

In AusTender, there are at least 15 amendments:

https://www.tenders.gov.au/Cn/Show/93b8feb0-d718-298a-f4ad-3e9a2338ec93

**Comment by skyuchukov-bp** [comment]
### Bug

It appears that the [findById](https://app.swaggerhub.com/apis/austender/ocds-api/1.1#/default/findById) API endpoint has a hard coded limit and returns only up to 10 Release objects for any single query.

Furthermore, the response does NOT contain the Pagination Links ([described here](https://github.com/austender/austender-ocds-api/blob/master/schema/release-package-schema.json)) which are present in the [findByDates](https://app.swaggerhub.com/apis/austender/ocds-api/1.1#/default/findByDates) endpoint.

### Impact

Following from the above, it means that **there is no way to retrieve all the data for a given contract if it has more than 9 amendments** (because 1 parent + 9 amendments = 10 Release objects).

A quick estimate (based on several years of historical data) shows that up to 1 per 1000 contracts end up having more than 9 amendments. 

### Reproduction

As an additional example to the one provided by @nickjevershed let's take [CN292558](https://www.tenders.gov.au/Cn/Show/017f2d5d-ce3f-1629-7217-3359b6c4cc37).

From the linked webpage we can see that this contract has more than 100 amendments, which shows that there are real-world cases where pagination is needed (the page size of the findByDates endpoint is 100 items).

As a contrast, here is the respective [findById API call](https://api.tenders.gov.au/ocds/findById/CN292558) for CN292558, it returns Releases objects for just: the parent, A1, A10-A17.
(Looking at some [other](https://api.tenders.gov.au/ocds/findById/CN82228) [cases](https://api.tenders.gov.au/ocds/findById/CN3394869) shows that the Releases are probably lexicographically ordered by their CN IDs - we get the first 10 items from the contract in this order).

**Comment by andrewlorien** [comment]
This is fixed!

**Comment by andrewlorien** [comment]
The problem with CN292558 and some other very old entries was related to the way amendments were processed over ten years ago.   The OCDS API now no longer publishes contracts published or amended before 01-01-2013, all contracts since then should include all amendments.
